version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/esdata/:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5044:5044"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  node-app:
    build: docker-elk-ui/
    ports:
      - "3000:3000"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  filebeat:
    build: filebeat/
    volumes:
      - /var/log/app/:/var/log/app/
    networks:
      - docker_elk
    depends_on:
      - logstash

networks:
  docker_elk:
    driver: bridge
